
## Customize checkout
#checkout:


## Customize dependencies
dependencies:
  pre:
    - export ROS_DISTRO=hydro
    - export CI_SOURCE_PATH=$(pwd)
    - export REPOSITORY_NAME=${PWD##*/}
    - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
    - wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -

  override:
    - sudo apt-get update
    - sudo apt-get install -y ros-$ROS_DISTRO-desktop
    - sudo rosdep init
    - rosdep update

  post:
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 99
    - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-3.4 99
    - gcc --version
    - clang --version

  # we automatically cache and restore many dependencies between
  # builds. If you need to, you can add custom paths to cache:
#  cache_directories:


## Customize database setup
#database:

## Customize test commands
test:
  override:
    - make 
    - make test
#  post:


## Custom notifications
#notify:
#  webhooks:
    # A list of hashes representing hooks. Only the url field is supported.
#    - url: https://someurl.com/hooks/circle



