language:
  - cpp
  - python

python:
  - "2.7"

compiler:
  - gcc

notifications:
  email:
    recipients:
      - aswinthomas@gmail.com
    on_success: change #[always|never|change] # default: change
    on_failure: change #[always|never|change] # default: always

before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export ROS_DISTRO=hydro
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y ros-$ROS_DISTRO-desktop
  - sudo rosdep init
  - rosdep update

#install: # Use this to install any prerequisites or dependencies necessary to run your build

before_script: # Use this to prepare your build for testing e.g. copy database configurations, environment variables, etc.
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - export ROS_PACKAGE_PATH=$ROS_PACKAGE_PATH:$CI_SOURCE_PATH
  - echo $ROS_PACKAGE_PATH
  - rospack profile 
  - roscd hull_cleaner

script: 
  - make
  - make test

